name: Run Unit Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - uses: actions/cache@v3
        with:
          path: ~/.cache/prisma
          key: ${{ runner.os }}-prisma-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-prisma-

      - run: npm ci

      - run: npm run test -- --ci > test-results.txt

      - uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.txt
